### ISSUE TITLE
Hello, have you uploaded your paper to the Internet yet?

### ISSUE THREAD

**Issue by jugechengzi** [shuaibo919/g-rat#1]
I am interested in your work, may I ask if the original paper is now available on the internet?

**Comment by shuaibo919** [comment]
not yet, maybe in may or June.

**Comment by shuaibo919** [comment]
Now is available online but not yet retrievable by Google Scholar.
here is the [link](https://ojs.aaai.org/index.php/AAAI/article/view/29783)
